### ISSUE TITLE
Feature: Allow resizing the status column

### ISSUE THREAD

**Issue by ferrariofilippo** [files-community/Files#10432]
### Description

`Status` column cannot be resized by the user.

### Steps To Reproduce

1. Open OneDrive folder
2. Try to resize `Status` column

### Steps to fix

User should be able resize Status column

### Files Version

Version: 2.3.55.0 OS Version: 10.0.22621.755

### Windows Version

Windows 11 Home Version 22H2 22621.755

### Relevant Assets/Logs

![Headers](https://user-images.githubusercontent.com/102259289/200517728-f9497266-54f0-4577-9250-7d0605e0f2c8.png)

**Comment by gave92** [comment]
That's on purpose as the contents of that column are fixed width (it's just an icon). The header text being cut is kinda ugly though.

**Comment by ferrariofilippo** [comment]
I was browsing the code and I noticed that still it has a `GridSplitter`.
I think we should remove it since we don't really need it.
At the moment it's not visible since its width is set to 0

**Comment by yaichenbaum** [comment]
We might as well make it resizable to be consistent with the other columns.

**Comment by ferrariofilippo** [comment]
@yair100 can you reopen this? It's still a problem. I'll check commit history to see when it was changed

**Comment by ferrariofilippo** [comment]
So, I analyzed the problem. I concluded that it is actually possible to resize `Sync Status` but only when its size is greater than 0. The real problem is that the column may have a width of 0 (this affects other folder-specific columns, such as `Deletion Date`). Now I need to figure out if this happens when the user clicks `Set as default` or when he restores overrides.

There is also another bug reintroduced with #10560: because we do not save `NormalMaxWidth`, the columns have no maximum width constraint after being resized. 
To reproduce this problem:
- Open a folder where you can view the `Sync Status` column (e.g., OneDrive).
- Resize the `Sync Status` column.
- Change folder and then go back to the first folder (in this example, OneDrive), this will reload columns settings.
- Try resizing the `Sync Status` column and see that there is no longer any width constraint
