### ISSUE TITLE
App crashing when moving/copying multiple files that are very large

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1222]
**Describe the bug**
When you move or copy multiple files that are very large (around 4GB) the app just crashes.

**To Reproduce**
1. Go to a folder with many files that are very large
2. Hit Control + A and then Control + X or Control + V
3. The app might crash.

**Desktop:**
 - OS: Windows 10 1903 18362.175
 - App version: v0.10.05

**Comment by duke7553** [comment]
There are some pretty major enhancements in this area (as of today) which are available from the StatusCenter branch. We hope to have these reliability improvements in preview very soon.

**Comment by duke7553** [comment]
@Jaiganeshkumaran Thank you for creating this feedback item. A solution to this issue is currently resolved in one of our active development branches and will be shipped after we've validated that everything works properly via code review. 

We will notify you when this feature is in a PR

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Can you upload the log file?

**Comment by jaigak** [comment]
@yair100 I don't have it anymore. I will try again

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Can you still reproduce this with v0.21.1?

**Comment by d2dyno1** [comment]
@duke7553 Are you currently working on this? Does it include modifying `IFilesystemOperations` in any way?

**Comment by duke7553** [comment]
@d2dyno1 Sorry, I'm not at the moment. We may need to utilize the Win32 primitives like CopyFileEx() for better reliability and precise byte-by-byte progress reporting.

**Comment by d2dyno1** [comment]
As I mentioned on Contributors channel, `CopyFileExA` does not seem to work like it's intended to

**Comment by duke7553** [comment]
@d2dyno1 That's a shame. They have it listed as usable in the UWP context, but I guess not.

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 3+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
