### ISSUE TITLE
Bug: Files crashes when scrolling up and down in a folder with 800+ files

### ISSUE THREAD

**Issue by clackwell** [files-community/Files#14469]
### Description

When scrolling up and down via keyboard in a folder with 800+ files Files sooner or later crashes

### Steps To Reproduce

1) Drop the files into an empty folder:

[create_test_files.bat.txt](https://github.com/files-community/Files/files/13943128/create_test_files.bat.txt)

2) Execute the file to create the number of files (and probably the file extensions play a role, too) needed for reproduction at my end.

3) Navigate into this folder again.

4) Click on the top most item.

5) Keep hitting the PageDown key. If the selection jumps to top again (another bug), click on the top item again, and keep pressing the PageDown key. After a few attempts Files crashes for me. Sometimes scrolling to the end and the start of the list via keyboard causes the crash. Sometimes using the scroll bar via mouse causes the crash.

This is of course not how I use Files, it is just the simplest way that I could find to reproduce a crash while scrolling through the list.

### Requirements

It should not crash. It seems like a race condition, perhaps in fetching the icons or other information.

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3007

### Log File

Since it crashed, and as far as I have seen, the log gets rewritten upon a new start, so I suspect it won't contain anything related to the crash.
[debug.log](https://github.com/files-community/Files/files/13943182/debug.log)

**Comment by yaira2** [comment]
@hishitetsu is this fixed in your recent PR?

**Comment by hishitetsu** [comment]
It is hard to say with all this. I have not been able to reproduce it.

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by clackwell** [comment]
I can still reproduce a crash with Files Preview 3.1.4.0.

To reproduce:

1. Enable "Configure tabs in dual pane mode".
2. Restart Files.
3. Open folder with test files created by [create_test_files.bat.txt](https://github.com/files-community/Files/files/13943128/create_test_files.bat.txt) in left pane.
4. Scroll to the bottom of the pane by clicking in the scroll bar, above the "down" button (do not use the button).
5. Once at bottom, select file "z886.zip".
6. Press and hold "Page Up" until the pane does not scroll any further (this is very often not the top of the list).
7. Repeat steps 3 to 6 for the right pane.
8. Repeat steps 3 to 6 for the left pane.

For me, Files Preview crash reliably at step 8, before it has scrolled down.

I still fail to let VS 2022 attach to the process before the crash, as well as debug the process when it crashes. But then I cannot tell if backtraces obtained by me would be any use for you folks.

**Comment by yaira2** [comment]
Which layout are you using? This might be a virtualization issue.

**Comment by clackwell** [comment]
> Which layout are you using? This might be a virtualization issue.

Ah, after a fresh Files Preview installation, I configured Details view, compact spacing, and ad-hoc open a dual pane in the tab. (Dual panes are off by default, still.) With this, the above mention steps start reproducing the issue.

Without compact spacing or without dual pane, the problem does not reproduce.

**Comment by yaira2** [comment]
Thanks for the feedback, this issue will be resolved in the next release.
