### ISSUE TITLE
Crash when immediately switching while a folder is being loaded

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/Files#1737]
**Describe the bug**
When you instantly switch while the folder loads, the app crashes.

**To Reproduce**
1. Create a new tab.
2. Click on a large folder pinned on the sidebar
3. Switch two the another tab very fast
4. App will crash

**Expected behavior**
App shouldn't crash and the refresh task should run in background.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 2004 
 - App version: v0.13.0 (Downloaded from the Microsoft Store)

**Additional context**
```
2020-08-14 14:08:36.7060|ERROR|Files.App|Object reference not set to an instance of an object.|System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.Filesystem.ItemViewModel.UpdateDirectoryInfo() + 0xf0
   at Files.Filesystem.ItemViewModel.<RapidAddItemsToCollectionAsync>d__70.MoveNext() + 0x970
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object) + 0x1e
   at System.Action`1.Invoke(T) + 0x28
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x33
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32) + 0xb8
   at __Interop.ForwardComStubs.Stub_11[TThis](__ComObject, Int32) + 0x24
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x3d
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x75
   at System.EventHandler`1.Invoke(Object, TEventArgs) + 0x2e
   at __Interop.Intrinsics.HasThisCall__23[TArg0](Object, IntPtr, Object, TArg0) + 0x36
   at Files!<BaseAddress>+0x12a44a0
```

**Comment by gave92** [comment]
@Jaiganeshkumaran could you check if this issue still exists on master? If we're lucky it got fixed with [this](https://github.com/files-community/files-uwp/pull/1718/files#diff-c66272bf7eb1f57b0287c4466394719bL1153)

**Comment by Jaiganeshkumaran** [comment]
@gave92 But that's for the recycle bin. I will build the latest branch and try it.

**Comment by gave92** [comment]
@Jaiganeshkumaran yeah the PR was for the recyclebin, but looking at the stacktrace it looks like that change may solve this issue too (error is NullReferenceException and the PR adds a null check to the `UpdateDirectoryInfo()` function)

**Comment by Jaiganeshkumaran** [comment]
@gave92 I tried it and it still seems to crash but this time it needs to be done extremely fast (< 50ms). Regular users may not notice it but we should fix it.

**Comment by duke7553** [comment]
@Jaiganeshkumaran Hello there.

Was your stack trace the same as before after @gave92 PR?

**Comment by Jaiganeshkumaran** [comment]
@gave92 Yes the same stack trace after @gave92's PR. Nothing changed.

**Comment by duke7553** [comment]
@Jaiganeshkumaran We recently made improvements that could affect this area. Can you still reproduce this issue on the latest Store build?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
