### ISSUE TITLE
The Files crash on startup after updating to 0.22.5

### ISSUE THREAD

**Issue by Tester09** [files-community/Files#2652]
**Describe the bug**
The app is crashing on startup

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 20277 fe_release]
 - App version: [v0.22.5]

**Additional context**
Reinstall and reset settings doesn't work

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5721538/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5721539/debug_fulltrust.txt)

**Comment by mdtauk** [comment]
me too

**Comment by tsvietOK** [comment]
fyi @gave92

**Comment by gave92** [comment]
A bug that was causing crash at startup was fixed after 0.22.5 in #2648 but this stacktrace looks different
@mdtauk could you share your `debug.txt` as well?

**Comment by mdtauk** [comment]
> A bug that was causing crash at startup was fixed after 0.22.5 in #2648 but this stacktrace looks different
> @mdtauk could you share your `debug.txt` as well?
> @tsvietOK is it working for you before and/or after #2648?

[debug.txt](https://github.com/files-community/Files/files/5721570/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5721572/debug_fulltrust.txt)

**Comment by gave92** [comment]
Aaand we have a third stacktrace different from the other two, great :/

**Comment by mdtauk** [comment]
Sorry @gave92

**Comment by tsvietOK** [comment]
@gave92 Version 0.22.5
[debug.txt](https://github.com/files-community/Files/files/5721577/debug.txt)

**Comment by gave92** [comment]
ok @tsvietOK your stacktrace is the one that (should) have been fixed in #2648

**Comment by tsvietOK** [comment]
@gave92 Just tested in debug mode on master branch, seems like issue fixed.

**Comment by mdtauk** [comment]
Not sure what you did, but 0.23.0 is not crashing for me

**Comment by gave92** [comment]
@mdtauk glad to hear that!
@Tester09 could you test if the issue is solved for you in version 0.23?

**Comment by Tester09** [comment]
@gave92  Unfortunately the app still crashing, even after re-install
[debug.txt](https://github.com/files-community/Files/files/5728570/debug.txt)

**Comment by yaichenbaum** [comment]
@Tester09 This issue should be resolved wtih #2663.
