### ISSUE TITLE
Add context menu item to pin exe file to taskbar

### ISSUE THREAD

**Issue by esibruti** [files-community/Files#5603]
**Is your feature request related to a problem?**
No

**Describe the solution**
I think it would be nice if Files had an option so that .exe programs could pin to the taskbar. 
Windows Explorer has this functionality.

**Screenshot**
![Captura de ecrã 2021-07-28 154720](https://user-images.githubusercontent.com/78214358/127343748-59aec290-60f6-4740-89b9-6bbd9a53734d.png)

**Describe alternatives you've considered**
The alternative is to have to use this function in Windows Explorer

**Scope**

| Capability | Priority |
| :---------- | :------- |
| add menu item to pin exe file to taskbar to the extended context menu | Could |

**System Information**
- OS Version: Windows 10 Home
   21H1
   19043.1110
   Windows Feature Experience Pack 120.2212.3530.0
- App version: v1.9.15.0

**Additional comment**
N/A

**Comment by yaichenbaum** [comment]
This is resolved in `main`.

**Comment by Josh-65** [comment]
This still is proberly an issue as the taskbar isnt an option only start menu. Unless it not in the 2.3.3.0 update?

**Comment by yaichenbaum** [comment]
That's correct, it hasn't been released yet.

**Comment by MalteTasler** [comment]
this is still an issue in the current preview version of the app.
