### ISSUE TITLE
Attempting to Navigate to My User Folder by Mouse Goes to `C:\Users\` Instead

### ISSUE THREAD

**Issue by ThisNekoGuy** [files-community/Files#8515]
### Description

For some reason, attempting to navigate to my user's folder by mouse specifically caused Files to navigate to the parent directory of that folder instead of to where I told it to.

When this occurred, I attempted to do so via the Address Bar (by clicking on Documents in Quick Access first, for speed) and Files seemed to ignore my request for a moment before navigating to `C:\Users\`  instead and throwing a notification that a problem occurred with the link to this bug form.

Attempting to click on my `User` name folder directly in the file manager window produced the same behavior after that but navigating to it by keyboard did not have this issue.

However, I will note that I have had Files running for an extended period of time and with about 3 or 4 tabs open; which may or may night have had something to do with it?

### Steps To Reproduce

1. Open `Files`
2. Click on `Documents` in the left panel
3. Click on the user directory in the `Address Bar` (which should be the parent directory)
4. Encounter the issue

### Expected behavior

`Files` should have navigated to the requested directory, by mouse, without issue.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19042.1526

### Windows Version

Windows 10 Home (Version	10.0.19042 Build 19042)

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8146160/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8146161/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this an issue in the preview version? https://files.community/download/preview

**Comment by ThisNekoGuy** [comment]
It does sort of still happen in the preview version but inconsistently:
what happens now is that it only _sometimes_ redirects to a different location and in the occurrence I just encountered, it redirected me to the root of the `C:\` drive; can't say I know why this happens though, I've no clue

I just kept repeating this process until it happened

**Comment by sthivaios** [comment]
> Is this an issue in the preview version? https://files.community/download/preview

It is not.

Uploading BUG#8515_Vid101.mp4…

**Comment by sthivaios** [comment]
> Can you share a screen recording? I'm having a hard time reproducing the issue.

You are probably having a hard time recreating this because it is not an issue anymore.

To @ThisNekoGuy, I suggest that you restart your computer, reset the app, or even uninstall the app and reinstall it. Also check if you have the latest version of the app. It might have been an old bug that was fixed with an update, so if there are any updates on microsoft store, install them. If you are gonna install the PRE (preview) version, I suggest you do that in a VM, because this can be unstable.

**Comment by Josh-65** [comment]
You don't need to install preview in a VM the worse that could happen is the app crashes. They already said it still happens but less and they are on the latest 2.3.47 which is also the preview.
